<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Managing your NAMESPACE}
-->

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  error = FALSE,
  tidy = FALSE
)
```

## Package namespace

The package `NAMESPACE` is one of the most confusing parts of building a package. Roxygen2 aims to make it as easy as possible to build a package that is a well-behaved member of the R ecosystem. This is a little frustrating at first, but soon becomes second-nature.

## Exports

For a function to be usable outside of your package, you must __export__ it. By default roxygen2 doesn't export anything from your package. If you want an object to be publically available, you must explicitly tag it with `@export`.

Use the following guidelines to decide what to export:

* Functions: export functions that you want to make available. Exported
  functions must be documented, and you must be cautious when changing their
  interface.

* Datasets: all datasets are publicly available. They exist outside of the
  package namespace and should not be exported.

* S3 classes: if you want others to be able to create instances of the class
  `@export` the constructor function.

* S3 generics: the generic is a function so `@export` if you want it to
  be usable outside the package

* S3 methods: every S3 method _must_ be exported, even if the generic is not.
  Otherwise the S3 method table will not be generated correctly and internal
  generics will not find the correct method.

* S4 classes: if you want others to be able to extend your class, `@export` it.
  If you want others to create instances of your class, but not extend it,
  `@export` the constructor function, but not the class.

      ```R
      # Can extend and create
      #' @export
      setClass("A")

      # Can extend, but constructor not exported
      #' @export
      B <- setClass("B")

      # Can create, but not extend
      #' @export C
      C <- setClass("C")

      # Can create and extend
      #' @export D
      #' @exportClass D
      D <- setClass("D")
      ```

* S4 generics: `@export` if you want the generic to be publicly usable.

* S4 methods: you only need to `@export` methods for generics that you
  did not define. But `@export`ing every method is a good idea as it
  will not cause problems and prevents you from forgetting to export an
  important method.

* RC classes: the same principles apply as for S4 classes. `@export`
  will only export the class.

## Imports

The `NAMESPACE` also controls which functions from other packages are made available to you package. There are five tags for importing objects into the package:

* `@import package` imports all functions, classes and methods from a package.

* `@importFrom package functiona functionb ...` imports selected functions.

* `@importClassesFrom package classa classb ...` imports selected S4 classes.

* `@importMethodsFrom package methoda methodb ...` imports selected S4 methods.

* `@useDynLib package` imports all compiled functions.

* `@useDynLib package routinea routineb` imports selected compiled functions.

* Any `@useDynLib` specification containing a comma, e.g.
  `@useDynLib mypackage, .registration = TRUE` will be inserted as is
  into the the NAMESPACE, e.g. `useDynLib(mypackage, .registration = TRUE)`

Only unique directives are saved to the `NAMESPACE` file, so you can
repeat them as needed to maintain a close link between the functions where
they are needed and the namespace file.
