test_that("rd_backref_sources parses single source file", {
  dir <- withr::local_tempdir()
  rd_file <- file.path(dir, "test.Rd")
  base::writeLines(
    c(
      "% Generated by roxygen2: do not edit by hand",
      "% Please edit documentation in R/foo.R",
      "\\name{foo}"
    ),
    rd_file
  )

  sources <- rd_backref_sources(rd_file, dir)
  expect_equal(sources, file.path(dir, "R/foo.R"))
})

test_that("rd_backref_sources parses multiple source files", {
  dir <- withr::local_tempdir()
  rd_file <- file.path(dir, "test.Rd")
  base::writeLines(
    c(
      "% Generated by roxygen2: do not edit by hand",
      "% Please edit documentation in R/foo.R, R/bar.R",
      "\\name{foo}"
    ),
    rd_file
  )

  sources <- rd_backref_sources(rd_file, dir)
  expect_equal(sources, file.path(dir, c("R/foo.R", "R/bar.R")))
})

test_that("rd_backref_sources handles wrapped backref lines", {
  dir <- withr::local_tempdir()
  rd_file <- file.path(dir, "test.Rd")
  base::writeLines(
    c(
      "% Generated by roxygen2: do not edit by hand",
      "% Please edit documentation in R/foo.R,",
      "%   R/bar.R",
      "\\name{foo}"
    ),
    rd_file
  )

  sources <- rd_backref_sources(rd_file, dir)
  expect_equal(sources, file.path(dir, c("R/foo.R", "R/bar.R")))
})

test_that("needs_roxygenize returns FALSE when all docs are current", {
  path <- local_package_copy(test_path("up-to-date"))
  suppressMessages(roxygenize(path))

  expect_false(needs_roxygenize(path))
})

test_that("needs_roxygenize returns TRUE when source is newer", {
  path <- local_package_copy(test_path("up-to-date"))
  suppressMessages(roxygenize(path))

  # Backdate the Rd file so source appears newer
  Sys.setFileTime(file.path(path, "man", "foo.Rd"), as.POSIXct("2000-01-01"))

  expect_snapshot(out <- needs_roxygenize(path))
  expect_true(out)
})
