// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// splitByWhitespace
std::vector<std::string> splitByWhitespace(std::string string);
RcppExport SEXP roxygen2_splitByWhitespace(SEXP stringSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type string(stringSEXP );
        std::vector<std::string> __result = splitByWhitespace(string);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// wrapString
std::string wrapString(std::string string, int width = 80, int indent = 2);
RcppExport SEXP roxygen2_wrapString(SEXP stringSEXP, SEXP widthSEXP, SEXP indentSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type string(stringSEXP );
        Rcpp::traits::input_parameter< int >::type width(widthSEXP );
        Rcpp::traits::input_parameter< int >::type indent(indentSEXP );
        std::string __result = wrapString(string, width, indent);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
