# Generated by cpp11: do not edit by hand

escapeExamples <- function(x) {
  .Call(`_roxygen2_escapeExamples`, x)
}

findEndOfTag <- function(string, is_code) {
  .Call(`_roxygen2_findEndOfTag`, string, is_code)
}

rdComplete <- function(string, is_code) {
  .Call(`_roxygen2_rdComplete`, string, is_code)
}

leadingSpaces <- function(lines) {
  .Call(`_roxygen2_leadingSpaces`, lines)
}

escape_rd_for_md_c <- function(text) {
  .Call(`_roxygen2_escape_rd_for_md_c`, text)
}

unescape_rd_for_md_c <- function(rd_text, id, tags) {
  .Call(`_roxygen2_unescape_rd_for_md_c`, rd_text, id, tags)
}

tokenise_block <- function(lines, file, offset) {
  .Call(`_roxygen2_tokenise_block`, lines, file, offset)
}

find_includes <- function(path) {
  .Call(`_roxygen2_find_includes`, path)
}

wrapUsage <- function(string, width, indent) {
  .Call(`_roxygen2_wrapUsage`, string, width, indent)
}
