# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

splitByWhitespace <- function(string) {
    .Call('roxygen2_splitByWhitespace', PACKAGE = 'roxygen2', string)
}

wrapString <- function(string, width = 80L, indent = 2L) {
    .Call('roxygen2_wrapString', PACKAGE = 'roxygen2', string, width, indent)
}

