# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rdComplete <- function(string) {
    .Call('roxygen2_rdComplete', PACKAGE = 'roxygen2', string)
}

leadingSpaces <- function(lines) {
    .Call('roxygen2_leadingSpaces', PACKAGE = 'roxygen2', lines)
}

preparse_block <- function(x) {
    .Call('roxygen2_preparse_block', PACKAGE = 'roxygen2', x)
}

preparse_file <- function(filePath) {
    .Call('roxygen2_preparse_file', PACKAGE = 'roxygen2', filePath)
}

splitByWhitespace <- function(string) {
    .Call('roxygen2_splitByWhitespace', PACKAGE = 'roxygen2', string)
}

wrapString <- function(string, width = 80L, indent = 2L) {
    .Call('roxygen2_wrapString', PACKAGE = 'roxygen2', string, width, indent)
}

