#' `roxy_tag` S3 constructor
#'
#' `roxy_tag()` is the constructor for tag objects.
#' `roxy_tag_warning()` generates a warning that gives the location of the tag.
#'
#' @keywords internal
#' @export
#' @param tag Tag name
#' @param raw Raw tag value, a string.
#' @param val Parsed tag value, typically a character vector, but sometimes
#'   a list. Usually filled in by `tag_parsers`
#' @param file,line Location of the tag
roxy_tag <- function(tag, raw, val = NULL, file = NA_character_, line = NA_integer_) {
  structure(
    list(
      file = file,
      line = line,
      raw = raw,
      tag = tag,
      val = val
    ),
    class = "roxy_tag"
  )
}

is.roxy_tag <- function(x) inherits(x, "roxy_tag")

#' @export
format.roxy_tag <- function(x, ..., file = NULL) {
  if (identical(x$file, file)) {
    file <- "line"
  } else if (is.na(x$file)) {
    file <- "????"
  } else {
    file <- basename(x$file)
  }
  line <- if (is.na(x$line)) "???" else format(x$line, width = 3)

  loc <- paste0("[", file, ":", line, "]")

  if (!is.null(x$raw)) {
    if (nchar(x$raw) > 50) {
      raw <-  paste0(substr(x$raw, 1, 47), "...")
    } else {
      raw <- x$raw
    }
  } else {
    raw <- "<generated by roxygen2>"
  }

  parsed <- if (is.null(x$val)) "{unparsed}" else "{parsed}"

  paste0(loc, " @", x$tag, " '", raw, "' ", parsed)
}

#' @export
print.roxy_tag <- function(x, ...) {
  cat_line(format(x, ...))
}

#' @export
#' @rdname roxy_tag
roxy_tag_warning <- function(x, ...) {
  message <- paste0(
    if (!is.na(x$file)) paste0("[", x$file, ":", x$line, "] "),
    "@", x$tag, " ",
    ...,
    collapse = " "
  )

  warning(message, call. = FALSE, immediate. = TRUE)
  NULL
}

roxy_tag_is_field <- function(tag) {
  inherits(tag$val, "roxy_field")
}

roxy_tag_eval <- function(tag, env) {
  tryCatch({
    expr <- parse(text = tag$val)
    out <- eval(expr, envir = env)

    if (!is.character(out)) {
      roxy_tag_warning(tag, "did not evaluate to a string")
    } else if (anyNA(out)) {
      roxy_tag_warning(tag, "result contained NA")
    } else {
      out
    }
  }, error = function(e) {
    roxy_tag_warning(tag, "failed with error:\n", e$message)
  })
}
